raw_accounts = [
    {'buff_phone': '17056635880', 'buff_pwd': 'Yqy@12345', 'steam_email': 'kyiaqmhoj6@suiyongsuiqi.com', 'steam_account': 'jerryin5', 'steam_pwd': 'txjhnnb12345'},
    {'buff_phone': '17022402286', 'buff_pwd': 'Yqy@12345', 'steam_email': 'pc7b8cadag@suiyongsuiqi.com', 'steam_account': 'jerryin6', 'steam_pwd': 'txjhnnb12345'},
    {'buff_phone': '16737138654', 'buff_pwd': 'Yqy@123456', 'steam_email': '591lmbcdvlg@suiyongsuiqi.com', 'steam_account': 'jerryin7', 'steam_pwd': 'txjhnnb12345'},
    {'buff_phone': '16571003870', 'buff_pwd': 'Yqy@1234567', 'steam_email': 'm33rb7ot31i@suiyongsuiqi.com', 'steam_account': 'jerryin8', 'steam_pwd': 'txjhnnb12345'},
    {'buff_phone': '17050573086', 'buff_pwd': 'Yqy@12345678', 'steam_email': 'nctux7if4ge@suiyongsuiqi.com', 'steam_account': 'jerryin9', 'steam_pwd': 'txjhnnb12345'},
    {'buff_phone': '16215707729', 'buff_pwd': 'Yqy@123456789', 'steam_email': 'g4hedeg664@suiyongsuiqi.com', 'steam_account': 'jerryin10', 'steam_pwd': 'yqy12345'},
    {'buff_phone': '', 'buff_pwd': '', 'steam_email': '', 'steam_account': '', 'steam_pwd': ''},
    {'buff_phone': '', 'buff_pwd': '', 'steam_email': '', 'steam_account': '', 'steam_pwd': ''},
    {'buff_phone': '', 'buff_pwd': '', 'steam_email': '', 'steam_account': '', 'steam_pwd': ''},
    {'buff_phone': '', 'buff_pwd': '', 'steam_email': '', 'steam_account': '', 'steam_pwd': ''},
    {'buff_phone': '', 'buff_pwd': '', 'steam_email': '', 'steam_account': '', 'steam_pwd': ''},
    {'buff_phone': '', 'buff_pwd': '', 'steam_email': '', 'steam_account': '', 'steam_pwd': ''},
    {'buff_phone': '', 'buff_pwd': '', 'steam_email': '', 'steam_account': '', 'steam_pwd': ''},
    {'buff_phone': '', 'buff_pwd': '', 'steam_email': '', 'steam_account': '', 'steam_pwd': ''},
    {'buff_phone': '', 'buff_pwd': '', 'steam_email': '', 'steam_account': '', 'steam_pwd': ''},
    {'buff_phone': '', 'buff_pwd': '', 'steam_email': '', 'steam_account': '', 'steam_pwd': ''},
    {'buff_phone': '', 'buff_pwd': '', 'steam_email': '', 'steam_account': '', 'steam_pwd': ''},
    {'buff_phone': '', 'buff_pwd': '', 'steam_email': '', 'steam_account': '', 'steam_pwd': ''},
    {'buff_phone': '', 'buff_pwd': '', 'steam_email': '', 'steam_account': '', 'steam_pwd': ''},
    {'buff_phone': '', 'buff_pwd': '', 'steam_email': '', 'steam_account': '', 'steam_pwd': ''},
    {'buff_phone': '', 'buff_pwd': '', 'steam_email': '', 'steam_account': '', 'steam_pwd': ''},
    {'buff_phone': '', 'buff_pwd': '', 'steam_email': '', 'steam_account': '', 'steam_pwd': ''},
    {'buff_phone': '', 'buff_pwd': '', 'steam_email': '', 'steam_account': '', 'steam_pwd': ''},
    {'buff_phone': '', 'buff_pwd': '', 'steam_email': '', 'steam_account': '', 'steam_pwd': ''},
    {'buff_phone': '', 'buff_pwd': '', 'steam_email': '', 'steam_account': '', 'steam_pwd': ''},
    {'buff_phone': '', 'buff_pwd': '', 'steam_email': '', 'steam_account': '', 'steam_pwd': ''},
    {'buff_phone': '', 'buff_pwd': '', 'steam_email': '', 'steam_account': '', 'steam_pwd': ''},
    {'buff_phone': '', 'buff_pwd': '', 'steam_email': '', 'steam_account': '', 'steam_pwd': ''},
    {'buff_phone': '', 'buff_pwd': '', 'steam_email': '', 'steam_account': '', 'steam_pwd': ''},
    {'buff_phone': '', 'buff_pwd': '', 'steam_email': '', 'steam_account': '', 'steam_pwd': ''},
]
all_accounts = [
    {'buff_phone': '17056635880', 'buff_pwd': 'Yqy@12345', 'steam_email': 'kyiaqmhoj6@suiyongsuiqi.com', 'steam_account': 'jerryin5', 'steam_pwd': 'txjhnnb12345'},
    {'buff_phone': '17022402286', 'buff_pwd': 'Yqy@12345', 'steam_email': 'pc7b8cadag@suiyongsuiqi.com', 'steam_account': 'jerryin6', 'steam_pwd': 'txjhnnb12345'},
    {'buff_phone': '16737138654', 'buff_pwd': 'Yqy@123456', 'steam_email': '591lmbcdvlg@suiyongsuiqi.com', 'steam_account': 'jerryin7', 'steam_pwd': 'txjhnnb12345'},
    {'buff_phone': '16571003870', 'buff_pwd': 'Yqy@1234567', 'steam_email': 'm33rb7ot31i@suiyongsuiqi.com', 'steam_account': 'jerryin8', 'steam_pwd': 'txjhnnb12345'},
    {'buff_phone': '17050573086', 'buff_pwd': 'Yqy@12345678', 'steam_email': 'nctux7if4ge@suiyongsuiqi.com', 'steam_account': 'jerryin9', 'steam_pwd': 'txjhnnb12345'},
    {'buff_phone': '16215707729', 'buff_pwd': 'Yqy@123456789', 'steam_email': 'g4hedeg664@suiyongsuiqi.com', 'steam_account': 'jerryin10', 'steam_pwd': 'yqy12345'},
    {'buff_phone': '', 'buff_pwd': '', 'steam_email': '', 'steam_account': '', 'steam_pwd': ''},
]